#pragma once
enum LAYER_PRINT_MODE {
    LAYER_PRINT_MODE_NONE = -1,
    LAYER_PRINT_MODE_NUMBER = 0,       
    LAYER_PRINT_MODE_WEIGHTS = 1,
    LAYER_PRINT_MODE_ALL = 3,
    LAYER_PRINT_MODE_TOTAL_WEIGHTS = 5,
    LAYER_PRINT_MODE_WEIGHT_RANGE = 6,
};
