enum LAYER_PRINT_MODE {
	LAYER_PRINT_MODE_NUMBER = 0, // for layer number
	LAYER_PRINT_MODE_WEIGHTS = 1,
	LAYER_PRINT_MODE_BIAS = 2,
	LAYER_PRINT_MODE_ALL = 3,
	LAYER_PRINT_MODE_WEIGHTS_BIAS = 4,
	LAYER_PRINT_MODE_WEIGHTS_NUMBER = 5
};