#pragma once
enum NEURON_PRINT_MODE
{
    NEURON_PRINT_MODES_NONE = -1,
    NEURON_PRINT_MODES_WEIGHTS = 0,
    NEURON_PRINT_MODES_BIAS = 1,
    NEURON_PRINT_MODES_ALL = 2,
    NEURON_PRINT_MODES_INPUTS = 3,
    NEURON_PRINT_MODES_OUTPUTS = 4,
    NEURON_PRINT_MODES_ACTIVATION_FUNC = 5,
    NEURON_PRINT_MODE_ID = 6
};
